pipeline{
	agent{
		docker{
			image 'jenkinsci/blueocean'
		}
	}
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

	stage('Security Test'){
	    steps {
	    	sh '''
			echo "Performing security testing"
			id


			echo "Current working directory"
			pwd
			ls


			echo "Checking root directory"
			ls -alh /root/.m2

			echo "Installing python and pipenv"
			apk add --update python python-dev py-pip && pip install pipenv && rm -rf /var/cache/apk/*

			python --version
			
			cd sectests
			pipenv install requests

			pipenv run python veracode-d-scan.py
		'''
	    }
	}
        stage('Deliver') {
            steps {
                sh 'pwd'
		sh './jenkins/scripts/deliver.sh'	
            }
        }
    }
}
